#### Tensors are a specialized data structure that are very similar to arrays and matrices. In PyTorch, we use tensors to encode the inputs and outputs of a model, as well as the model’s parameters. Tensors are similar to NumPy’s ndarrays, except that tensors can run on GPUs or other hardware accelerators


In [1]:
import torch 
import numpy as np

In [2]:
## Tensor can be number,vectore,matrix or any nd array

In [3]:
t1 = torch.tensor(4.) ## 4. means 4.0 it means we are creating floating types
t1

tensor(4.)

In [4]:
## Vector
t2 = torch.tensor([1.,2,3]) ## Datatype in tensor will be same so in this case int will be converted to float
t2

tensor([1., 2., 3.])

In [5]:
# Matrix
t3 = torch.tensor([[5., 6], 
                   [7, 8], 
                   [9, 10]])
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [6]:
# 3-dimensional array
t4 = torch.tensor([
    [[11, 12, 13], 
     [13, 14, 15]], 
    [[15, 16, 17], 
     [17, 18, 19.]]])
t4

tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])

In [7]:
## The difference between list of list and tensor is that tensore will be in regular shape e.g it will give errror
# Matrix
t3 = torch.tensor([[5., 6], 
                   [7, 8], 
                   [9, 10,11]])
t3

ValueError: expected sequence of length 2 at dim 1 (got 3)

In [8]:
## Shape
print(t3.shape)
print(t4.shape)

torch.Size([3, 2])
torch.Size([2, 2, 3])


In [9]:
## Creating tensor from numpy array
data = [[1,2],[3,4]]
np_array = np.array(data)
x_data = torch.from_numpy(np_array)
x_data

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [10]:
## The new tensor retains the properties (shape, datatype) of the argument tensor, unless explicitly overridden.
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]], dtype=torch.int32) 

Random Tensor: 
 tensor([[0.3522, 0.6166],
        [0.8282, 0.4048]]) 



In [11]:
## shape is a tuple of tensor dimensions. In the functions below, it determines the dimensionality of the output tensor.

shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)


print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.4769, 0.0207, 0.2408],
        [0.8498, 0.9665, 0.4043]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


##### Tensor attributes describe their shape, datatype, and the device on which they are stored.

In [12]:
tensor = torch.rand(3,4)
print(f"Shape of tensor is: \n{tensor.shape}\n")
print(f"Datatype of tensor is: \n{tensor.dtype}\n")
print(f"Device tensor is stored on: \n{tensor.device}\n")
tensor

Shape of tensor is: 
torch.Size([3, 4])

Datatype of tensor is: 
torch.float32

Device tensor is stored on: 
cpu



tensor([[0.4992, 0.8274, 0.5915, 0.4749],
        [0.6980, 0.1682, 0.3249, 0.0356],
        [0.0100, 0.0931, 0.3307, 0.4032]])

## Operation On Tensor

#### Over 100 tensor operations, including arithmetic, linear algebra, matrix manipulation (transposing, indexing, slicing), 

#### Each of these operations can be run on the GPU (at typically higher speeds than on a CPU). If you’re using Colab, allocate a GPU by going to Runtime > Change runtime type > GPU.

#### By default, tensors are created on the CPU. We need to explicitly move tensors to the GPU using .to method (after checking for GPU availability). Keep in mind that copying large tensors across devices can be expensive in terms of time and memory!

In [13]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
    tensor = tensor.to('cuda')
      

In [14]:
tensor = torch.ones(4, 4)
print('First row: ',tensor[0])
print('First column: ', tensor[:, 0])
print('Last column:', tensor[..., -1])
tensor[:,1] = 0
print(tensor)

First row:  tensor([1., 1., 1., 1.])
First column:  tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [ ]:
## Jooining the tensor

In [15]:
t1 = torch.cat([tensor, tensor, tensor],dim=0)
print(t1)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [16]:
t1 = torch.cat([tensor, tensor, tensor],dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [17]:
# This computes the matrix multiplication between two tensors. y1, y2, y3 will have the same value
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)



tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [18]:

# This computes the element-wise product. z1, z2, z3 will have the same value
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [19]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


In [20]:
tensor.shape

torch.Size([4, 4])

In [21]:
# Create tensors.
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)
x, w, b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

We've created three tensors: x, w, and b, all numbers. w and b have an additional parameter requires_grad set to True. We'll see what it does in just a moment.

Let's create a new tensor y by combining these tensors.

In [22]:
y = w*x + b
y

tensor(17., grad_fn=<AddBackward0>)

As expected, y is a tensor with the value 3 * 4 + 5 = 17. What makes PyTorch unique is that we can automatically compute the derivative of y w.r.t. the tensors that have requires_grad set to True i.e. w and b. This feature of PyTorch is called autograd (automatic gradients).

To compute the derivatives, we can invoke the .backward method on our result y.

In [23]:
# Compute derivatives
y.backward()

The derivatives of y with respect to the input tensors are stored in the .grad property of the respective tensors.

In [24]:
# Display gradients
print('dy/dx:', x.grad)
print('dy/dw:', w.grad)
print('dy/db:', b.grad)

dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(1.)


As expected, dy/dw has the same value as x, i.e., 3, and dy/db has the value 1. Note that x.grad is None because x doesn't have requires_grad set to True.

The "grad" in w.grad is short for gradient, which is another term for derivative. The term gradient is primarily used while dealing with vectors and matrices.

In [25]:
x  = np.array([[1,2],[3,4]])

In [26]:
t = torch.tensor(x) ## It create copy of data
t1 = torch.from_numpy(x) ## It uses same space and memory

In [29]:
x.dtype,t1.dtype

(dtype('int32'), torch.int32)

In [30]:
torch_numpy = t1.numpy()

In [32]:
torch_numpy

array([[1, 2],
       [3, 4]])